### ISSUE TITLE
Enhancement: Full-Size Table Rows Widget

### ISSUE THREAD

**Issue by SystemicArcana** [Dive576/DIVE#2]
When no axis is selected for display and a Table Rows widget has been created by adding a Table Row to the DIVE window, the Table Rows widget still only takes up half of the available space. Should the empty plotting widget window be removed when no axis is selected so that other widgets like Table Rows can properly fill the window space?

**Comment by Dive576** [comment]
Just made a quick update to hide the plotting canvas if an axis isn't being displayed.
